# Generated by Django 5.1.4 on 2024-12-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('puzzle_id', models.IntegerField()),
                ('response', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('attempts', models.IntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('puzzles_solved', models.IntegerField(default=0)),
            ],
        ),
    ]
